name: Update users data
on:
  issues:
    types: [opened]
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Make and commit changes
        run: |
          python src/add_users.py ${{ github.event.issue.title }}
          python src/build_table.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add bin/users.json
          git diff --cached --quiet -- bin/users.json || git commit -m "Update users" bin/users.json
          git add readme.md
          git diff --cached --quiet -- readme.md || git commit -m "Add new users to leaderboard" readme.md
          git push

      - name: Close Issue
        run: |
          gh issue close ${{ github.event.issue.number }} -c "Auto close"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
